version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_recognition
    volumes:
      - ./BD_vehicle_recognition.sql :/docker-entrypoint-initdb.d/BD_vehicle_recognition.sql     
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vehicle_recognition
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres_recognition
    network_mode: host

  backend:
    container_name: back_end
    build:
      dockerfile: ./back-end/deployment/DockerFile
    network_mode: host

  recognition:
    container_name: client_recognition
    build:
      dockerfile: ./clientRecognition/DockerFile
    network_mode: host

  login:
    container_name: front_end_login
    build:
      dockerfile: ./front-end/login/DockerFile
    network_mode: host

  admin:
    container_name: front_end_admin
    build:
      dockerfile: ./front-end/admin/DockerFile
    network_mode: host

  vigilante:
    container_name: front_end_vigilante
    build:
      dockerfile: ./front-end/vigilante/DockerFile
    network_mode: host