version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres_recognition
    volumes:
      - ./BD_vehicle_recognition.sql :/docker-entrypoint-initdb.d/BD_vehicle_recognition.sql     
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vehicle_recognition
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432